source 'https://rubygems.org'

ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'

# DBMS:
instance_eval(File.read(File.join(File.dirname(__FILE__), 'Gemfile_dbms')))

# Use SCSS for stylesheets
gem 'sass-rails'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Every internal <a> link makes the body reload via AJAX instead of reloading the entire page.
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

##END default file

gem 'foreman'

# Use unicorn as the app server
gem 'unicorn'
#gem 'unicorn-rails'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

# Login:
gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'

gem 'breadcrumbs_on_rails'

gem 'haml-rails'

# Custom settings:
gem 'settingslogic'

# Dev data:
gem 'faker'
#gem 'seed-fu'
