source 'https://rubygems.org'

ruby '2.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'

# DBMS:
instance_eval(File.read(File.join(File.dirname(__FILE__), 'Gemfile_dbms')))

# Use SCSS for stylesheets
gem 'sass-rails', '4.0.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.0.4'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '1.3.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Every internal <a> link makes the body reload via AJAX instead of reloading the entire page.
gem 'turbolinks', '1.3.1'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
gem 'unicorn', '4.7.0'
#gem 'unicorn-rails'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'

gem 'faker'

gem 'foreman'
